# Generated by Django 5.2.3 on 2025-06-25 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_bookreview_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreview",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
